### ISSUE TITLE
Karekod oluşturma ve link kısaltma hatası

### ISSUE THREAD

**Issue by sametatabasch** [GiresunTBMYOBilgisayarProgramciligi/DuyuruPaneli#13]
link kısaltma işleminde bir hata olduğu  link eklenen duyurular eklenirken hata veriyor.

[Fri Sep 01 16:24:05.113623 2023] [php7:error] [pid 357995] [client 172.68.51.58:26288] PHP Fatal error:  Uncaught Exception: {"status_code":410,"status_txt":"PERMANENTLY_REMOVED","data":[]} in /home/sametatabasch/gencbilisim.net/DuyuruPaneli/vendor/gabrielkaputa/bitly/src/Bitly.php:42\nStack trace:\n#0 /home/sametatabasch/gencbilisim.net/DuyuruPaneli/vendor/gabrielkaputa/bitly/src/Bitly.php(82): GabrielKaputa\\Bitly\\Bitly->sendRequest()\n#1 /home/sametatabasch/gencbilisim.net/DuyuruPaneli/App/AnnouncementController.php(88): GabrielKaputa\\Bitly\\Bitly->shortenUrl()\n#2 /home/sametatabasch/gencbilisim.net/DuyuruPaneli/App/AnnouncementController.php(32): App\\AnnouncementController->createQrCode()\n#3 /home/sametatabasch/gencbilisim.net/DuyuruPaneli/App/AjaxController.php(38): App\\AnnouncementController->saveNewAnnouncement()\n#4 [internal function]: App\\AjaxController->saveAnnouncement()\n#5 /home/sametatabasch/gencbilisim.net/DuyuruPaneli/admin/ajax.php(18): call_user_func()\n#6 {main}\n  thrown in /home/sametatabasch/gencbilisim.net/DuyuruPaneli/vendor/gabrielkaputa/bitly/src/Bitly.php on line 42, referer: https://tmyoduyuru.gencbilisim.net/admin/

**Comment by sametatabasch** [comment]
https://app.yourls.org/
Twitter yerine kendi link kısaltma uygulamamı oluşturup kullanabilirim. Yada başka bir api
